#!/usr/bin/env bash
# Installs, configures, and starts the server
sudo su
apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
chown -R "$USER:$USER" /var/www/html/*
chmod -R 755 /var/www/html
echo 'Hello World!' > /var/www/html/index.html	

SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		try_files \$uri \$uri/ =404;
	}
}"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi