#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me
sudo su
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
chown -R "$USER:$USER" /var/www/html/*
chmod -R 755 /var/www/html
echo "Hello World!" > /var/www/html/index.html

sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/ismailchiba permanent;/" /etc/nginx/sites-available/default
service nginx start