#!/usr/bin/env bash
# Fixes the nginx listening port and reloads the nginx master process
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx stop
